export const ROUTES = {
	home: '/',
	news: '/news',
	events: '/events',
	articles: '/articles',
	register: '/register',
	specialists: '/specialists',
	store: '/store',
	about: '/about',
	donate: '/donate',
	contacts: '/contacts',
	privacy: '/privacy',
	agreement: '/agreement',
	cookies: '/cookies',
};
